# Generated by Django 6.0.2 on 2026-02-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_codename', models.CharField(max_length=50)),
                ('last_checkin', models.DateTimeField()),
                ('next_expected', models.DateTimeField()),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('MISSED', 'Missed'), ('CRITICAL', 'Critical')], default='ON_TIME', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeadDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_codename', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('coords', models.CharField(blank=True, max_length=50)),
                ('next_scheduled', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('COMPROMISED', 'Compromised')], default='SCHEDULED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_codename', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('threat_level', models.IntegerField(default=3)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.JSONField(default=list)),
                ('encryption_type', models.CharField(default='AES-256-GCM', max_length=50)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('PRIORITY', 'Priority'), ('FLASH', 'Flash'), ('CRITIC', 'CRITIC')], default='ROUTINE', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('encrypted_content', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comms.thread')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
