# Generated by Django 6.0.2 on 2026-02-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=50, unique=True)),
                ('real_name', models.CharField(max_length=200)),
                ('cover_identity', models.CharField(blank=True, max_length=200)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(max_length=50)),
                ('clearance', models.CharField(choices=[('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret'), ('COSMIC', 'Cosmic Top Secret')], default='SECRET', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('COMPROMISED', 'Compromised'), ('EXTRACTED', 'Extracted'), ('MIA', 'Missing in Action'), ('TRAINING', 'Training')], default='TRAINING', max_length=20)),
                ('division', models.CharField(choices=[('RAW', 'R&AW'), ('IB', 'IB'), ('DIA', 'DIA'), ('NTRO', 'NTRO')], default='RAW', max_length=10)),
                ('skills', models.JSONField(default=dict)),
                ('handler', models.CharField(blank=True, max_length=100)),
                ('deployed_country', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('app_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('languages', models.JSONField(default=list)),
                ('physical_score', models.IntegerField()),
                ('iq_score', models.IntegerField()),
                ('service', models.CharField(choices=[('MILITARY', 'Military'), ('POLICE', 'Police'), ('CIVILIAN', 'Civilian'), ('INTELLIGENCE', 'Intelligence')], max_length=20)),
                ('specialization', models.CharField(choices=[('HUMINT', 'HUMINT'), ('SIGINT', 'SIGINT'), ('CYBER', 'Cyber Ops'), ('COVERT_OPS', 'Covert Ops'), ('ANALYSIS', 'Analysis'), ('COUNTER_INTEL', 'Counter-Intelligence')], max_length=20)),
                ('stage', models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('FIELD_TEST', 'Field Test'), ('INTERVIEW', 'Interview'), ('POLYGRAPH', 'Polygraph'), ('CLEARANCE', 'Clearance'), ('INDUCTED', 'Inducted'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('priority', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('agency', models.CharField(choices=[('RAW', 'R&AW'), ('IB', 'IB'), ('DIA', 'DIA'), ('NTRO', 'NTRO')], max_length=10)),
                ('clearance', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('bio_hash', models.CharField(blank=True, max_length=64)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('issued', models.DateField(auto_now_add=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(max_length=20)),
                ('requested_level', models.CharField(max_length=20)),
                ('supervisor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_requests', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('duration_weeks', models.IntegerField(default=4)),
                ('difficulty', models.IntegerField(default=3)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='agents.agent')),
            ],
            options={
                'unique_together': {('agent', 'module_name')},
            },
        ),
    ]
