# Generated by Django 6.0.2 on 2026-02-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_id', models.CharField(max_length=20, unique=True)),
                ('codename', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INFILTRATION', 'Infiltration'), ('SURVEILLANCE', 'Surveillance'), ('EXTRACTION', 'Extraction'), ('SABOTAGE', 'Sabotage'), ('ASSASSINATION', 'Assassination'), ('INTELLIGENCE', 'Intelligence Gathering'), ('RECON', 'Reconnaissance'), ('ESCORT', 'Escort')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('risk_level', models.IntegerField(default=3)),
                ('duration', models.CharField(max_length=50)),
                ('required_skills', models.JSONField(default=list)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret'), ('COSMIC', 'Cosmic')], default='SECRET', max_length=20)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='UNASSIGNED', max_length=20)),
                ('briefing', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployed_date', models.DateTimeField(auto_now_add=True)),
                ('last_checkin', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ON_MISSION', 'On Mission'), ('RETURNING', 'Returning'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed')], default='ON_MISSION', max_length=20)),
                ('days_deployed', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='agents.agent')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='operations.mission')),
            ],
        ),
    ]
