# Generated by Django 6.0.2 on 2026-02-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret'), ('COSMIC', 'Cosmic')], default='SECRET', max_length=20)),
                ('category', models.CharField(choices=[('INTELLIGENCE', 'Intelligence Report'), ('MILITARY', 'Military'), ('DIPLOMATIC', 'Diplomatic Cable'), ('ECONOMIC', 'Economic'), ('NUCLEAR', 'Nuclear'), ('CYBER', 'Cyber'), ('INTERNAL', 'Internal Memo')], default='INTELLIGENCE', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('content_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
